package chronosacaria.mcdw.enums;

public enum DaggersID {
    DAGGER_BACKSTABBER,
    DAGGER_CHILL_GALE_KNIFE,
    DAGGER_DAGGER,
    DAGGER_FANGS_OF_FROST,
    DAGGER_MOON,
    DAGGER_RESOLUTE_TEMPEST_KNIFE,
    DAGGER_SHEAR_DAGGER,
    DAGGER_SWIFT_STRIKER,
    DAGGER_TEMPEST_KNIFE,
    DAGGER_THE_BEGINNING,
    DAGGER_THE_END,
    DAGGER_VOID_TOUCHED_BLADE
}