package chronosacaria.mcdw.enums;

public enum HammersID {
    HAMMER_BONECLUB,
    HAMMER_BONE_CUDGEL,
    HAMMER_FLAIL,
    HAMMER_GRAVITY,
    HAMMER_GREAT_HAMMER,
    HAMMER_MACE,
    HAMMER_STORMLANDER,
    HAMMER_SUNS_GRACE
}