package chronosacaria.mcdw.enums;

public enum MeleeWeaponID {
    // Swords


    // Axes


    // Double Axes

    // Daggers
    DAGGER_DAGGER,
    DAGGER_FANGS_OF_FROST,
    DAGGER_MOON,
    DAGGER_SHEAR_DAGGER,
    DAGGER_TEMPEST_KNIFE,
    DAGGER_RESOLUTE_TEMPEST_KNIFE,
    DAGGER_CHILL_GALE_KNIFE,
    DAGGER_BACKSTABBER,
    DAGGER_SWIFT_STRIKER,
    DAGGER_VOID_TOUCHED_BLADE,
    DAGGER_THE_BEGINNING,
    DAGGER_THE_END,

    // Soul Daggers
    DAGGER_SOUL_KNIFE,
    DAGGER_ETERNAL_KNIFE,
    SWORD_TRUTHSEEKER,

    // Hammers
    HAMMER_GREAT,
    HAMMER_STORMLANDER,
    HAMMER_GRAVITY,
    HAMMER_MACE,
    HAMMER_FLAIL,
    HAMMER_SUNS_GRACE,
    HAMMER_BONECLUB,
    HAMMER_BONE_CUDGEL,

    // Gauntlets
    GAUNTLET_GAUNTLET,
    GAUNTLET_MAULERS,
    GAUNTLET_SOUL_FISTS,

    // Sickles
    SICKLE_SICKLE,
    SICKLE_NIGHTMARES_BITE,
    SICKLE_LAST_LAUGH_GOLD,
    SICKLE_LAST_LAUGH_SILVER,

    // Scythes
    SICKLE_JAILORS_SCYTHE,
    SICKLE_SOUL_SCYTHE,
    SICKLE_FROST_SCYTHE,
    SICKLE_SKULL_SCYTHE,

    // Picks
    PICK_DIAMOND_PICKAXE_VAR,
    PICK_MOUNTAINEER_PICK,
    PICK_HOWLING_PICK,
    PICK_HAILING_PINNACLE,

    // Glaives
    SPEAR_GLAIVE,
    SPEAR_GRAVE_BANE,
    SPEAR_VENOM_GLAIVE,
    SPEAR_CACKLING_BROOM,

    // Spears
    SPEAR_SPEAR,
    SPEAR_WHISPERING_SPEAR,
    SPEAR_FORTUNE,

    // Staves
    STAFF_BATTLESTAFF,
    STAFF_GROWING_STAFF,
    STAFF_BATTLESTAFF_OF_TERROR,

    // Whips
    WHIP_WHIP,
    WHIP_VINE_WHIP
}
