package chronosacaria.mcdw.enums;

public enum SettingsID {
    ENABLE_OP_ENCHANTMENT_MIXING,
    LEECHING_CAN_BE_MIXED_WITH_HEALING,
    EXTRA_XP_HEALING,
    AREA_OF_EFFECT_ENCHANTS_DONT_AFFECT_PLAYERS,
    ENABLE_INNATE_ENCHANTMENTS
}
