package chronosacaria.mcdw.enums;

public enum SwordsID {
    SWORD_CLAYMORE,
    BROADSWORD,
    FROST_SLAYER,
    HEARTSTEALER,
    GREAT_AXEBLADE,
    RAPIER,
    BEE_STINGER,
    FREEZING_FOIL,
    CUTLASS,
    NAMELESS_BLADE,
    DANCERS_SWORD,
    KATANA,
    MASTERS_KATANA,
    DARK_KATANA,
    IRON_SWORD_VAR,
    DIAMOND_SWORD_VAR,
    HAWKBRAND,
    SINISTER_SWORD,
    BROKEN_SAWBLADE,
    MECHANIZED_SAWBLADE,
    CORAL_BLADE,
    SPONGE_STRIKER,
    OBSIDIAN_CLAYMORE,
    THE_STARLESS_NIGHT
}
