#
# Timefall Development License 1.2
# Copyright (c) 2025. Chronosacaria, Kluzzio, Timefall Development. All Rights Reserved.
#
# This software's content is licensed under the Timefall Development License 1.2. You can find this license information here: https://github.com/Timefall-Development/Timefall-Development-Licence/blob/main/TimefallDevelopmentLicense1.2.txt
#

loom.platform=neoforge
yarn_mappings_patch_neoforge_version=1.21+build.4